### ISSUE TITLE
Install tooling, add config files, boilerplate

### ISSUE THREAD

**Issue by franzwollang** [devhausleipzig/camp5-frontend-app#4]
Requirements:
- TypeScript
- Tailwind
- React
- React Router DOM
- PostCSS
- Autoprefixer
- Axios
- Vite
- JSON server

Suggestions:
- Headless UI (tailwind-friendly components)
- Lodash

**Comment by aronvaupel** [comment]
Done.

**Comment by franzwollang** [comment]
Let's make the procedure to close issues after review.
